fo=open(r"C:\Users\User\Desktop\Pythonpractice04\Day09\abc2.txt","w+")
inpstr=input('Enter text:')
fo.write(inpstr)
inpstr=input('Enter text:')
fo.write(inpstr)
fo.close()
print('Text written to file')
